
export type RankingEntry = {
  rank: number;
  name: string;
  location: string;
  type: "Country Club" | "School" | "Community";
  championships: number;
  winRate: string;
  record: string;
  points: number;
  trend: number; // Positive for up, negative for down, 0 for neutral
};

export const rankingData: RankingEntry[] = [
  {
    rank: 1,
    name: "Cottonwood Valley Country Club",
    location: "Irving, TX",
    type: "Country Club",
    championships: 9,
    winRate: "85.5%",
    record: "47-8",
    points: 1354,
    trend: 59,
  },
  {
    rank: 2,
    name: "Test Sports Club",
    location: "Test City, TS",
    type: "Country Club",
    championships: 9,
    winRate: "95.7%",
    record: "44-2",
    points: 1336,
    trend: 18,
  },
  {
    rank: 3,
    name: "Royal Oaks Country Club",
    location: "Dallas, TX",
    type: "Country Club",
    championships: 9,
    winRate: "95.1%",
    record: "39-2",
    points: 1286,
    trend: 22,
  },
  {
    rank: 4,
    name: "Youth Sports Academy",
    location: "Test City, TS",
    type: "School",
    championships: 8,
    winRate: "89.1%",
    record: "49-6",
    points: 1278,
    trend: -12,
  },
  {
    rank: 5,
    name: "Community Center",
    location: "Test City, TS",
    type: "Community",
    championships: 8,
    winRate: "88.9%",
    record: "48-6",
    points: 1268,
    trend: 0,
  },
  {
    rank: 6,
    name: "Test Sports Club",
    location: "Test City, TS",
    type: "Country Club",
    championships: 9,
    winRate: "84.4%",
    record: "38-7",
    points: 1266,
    trend: 28,
  },
  {
    rank: 7,
    name: "Country Club A",
    location: "Test City, TS",
    type: "Country Club",
    championships: 9,
    winRate: "85.0%",
    record: "34-6",
    points: 1228,
    trend: 59,
  },
  {
    rank: 8,
    name: "Youth Sports Academy",
    location: "Test City, TS",
    type: "School",
    championships: 8,
    winRate: "97.5%",
    record: "39-1",
    points: 1188,
    trend: -5,
  },
  {
    rank: 9,
    name: "Test Sports Club",
    location: "Test City, TS",
    type: "Country Club",
    championships: 9,
    winRate: "88.7%",
    record: "28-14",
    points: 1152,
    trend: 64,
  },
  {
    rank: 10,
    name: "Las Colinas Country Club",
    location: "Irving, TX",
    type: "Country Club",
    championships: 9,
    winRate: "83.9%",
    record: "26-5",
    points: 1150,
    trend: 10,
  },
  {
    rank: 11,
    name: "Stonebriar Country Club",
    location: "Frisco, TX",
    type: "Country Club",
    championships: 9,
    winRate: "56.1%",
    record: "23-18",
    points: 1094,
    trend: 37,
  },
  {
    rank: 12,
    name: "Cottonwood Valley Country Club",
    location: "Irving, TX",
    type: "Country Club",
    championships: 7,
    winRate: "80.0%",
    record: "40-10",
    points: 1080,
    trend: 81,
  },
  {
    rank: 13,
    name: "Team Beta",
    location: "Test City, TS",
    type: "School",
    championships: 8,
    winRate: "89.2%",
    record: "27-12",
    points: 1048,
    trend: 36,
  },
  {
    rank: 14,
    name: "Bent Tree Country Club",
    location: "Dallas, TX",
    type: "Country Club",
    championships: 6,
    winRate: "82.7%",
    record: "43-9",
    points: 1012,
    trend: 20,
  },
  {
    rank: 15,
    name: "Test Sports Club",
    location: "Test City, TS",
    type: "Country Club",
    championships: 8,
    winRate: "77.0%",
    record: "21-6",
    points: 990,
    trend: 78,
  },
  {
    rank: 16,
    name: "The Clubs of Prestonwood",
    location: "Dallas, TX",
    type: "Country Club",
    championships: 6,
    winRate: "70.0%",
    record: "42-18",
    points: 984,
    trend: 12,
  },
  {
    rank: 17,
    name: "Test Sports Club",
    location: "Test City, TS",
    type: "Country Club",
    championships: 7,
    winRate: "90.6%",
    record: "29-3",
    points: 984,
    trend: 51,
  },
  {
    rank: 18,
    name: "Four Seasons Resort & Club",
    location: "Irving, TX",
    type: "Country Club",
    championships: 7,
    winRate: "65.9%",
    record: "27-14",
    points: 842,
    trend: 73,
  },
  {
    rank: 19,
    name: "Timarron Country Club",
    location: "Southlake, TX",
    type: "Country Club",
    championships: 7,
    winRate: "66.7%",
    record: "26-13",
    points: 934,
    trend: 66,
  },
  {
    rank: 20,
    name: "Youth Sports Academy",
    location: "Test City, TS",
    type: "School",
    championships: 6,
    winRate: "91.9%",
    record: "34-3",
    points: 934,
    trend: -7,
  },
  {
    rank: 21,
    name: "Four Seasons Resort & Club",
    location: "Irving, TX",
    type: "Country Club",
    championships: 7,
    winRate: "73.5%",
    record: "25-9",
    points: 932,
    trend: 69,
  },
  {
    rank: 22,
    name: "Youth Sports Academy",
    location: "Test City, TS",
    type: "School",
    championships: 9,
    winRate: "50.0%",
    record: "3-3",
    points: 824,
    trend: 51,
  },
  {
    rank: 23,
    name: "Test Sports Club",
    location: "Test City, TS",
    type: "Country Club",
    championships: 6,
    winRate: "100.0%",
    record: "31-0",
    points: 910,
    trend: 0,
  },
  {
    rank: 24,
    name: "Team Alpha",
    location: "Test City, TS",
    type: "School",
    championships: 8,
    winRate: "48.7%",
    record: "14-16",
    points: 908,
    trend: 63,
  },
  {
    rank: 25,
    name: "Community Center",
    location: "Test City, TS",
    type: "Community",
    championships: 6,
    winRate: "79.5%",
    record: "31-8",
    points: 894,
    trend: 78,
  }
];
